### ISSUE TITLE
6dof motion solver tutorial

### ISSUE THREAD

**Issue by efirvida** [precice/openfoam-adapter#108]
I want to simulate rotatory machinery, with motion driven by the fluid, I know how to do it in OpenFOAM, But now I want to have the deformations of the body using FSI. Basically I think that can be done modifying the classic propeller tutorial.

thanks!

**Comment by MakisH** [comment]
Dear @efirvida,

are you asking on how to do it? The best place to discuss this would be on our new [Discourse forum](https://precice.discourse.group/), as we keep issues only for bugs / feature requests. Could you please repost your question there, together with some more details to understand your setup.
