### ISSUE TITLE
Docker container for the adapter with precice 

### ISSUE THREAD

**Issue by ykhedar** [precice/openfoam-adapter#11]
Hi, I was wondering if the team is planning to add docker images some time soon. I found that @ludcila already created some docker container for her thesis. I created one for testing the adapter using Ubuntu 16.10-artful(since **boost** is pre-installed :) ). The link to the repository is:

[precice-docker](https://bitbucket.org/khedar/precice/). 

Would be happy to create a Pull request or feel free to use the docker files as the team feels fit. :)

I also observed that precice uses travis CI. It would be really practical if travis can build the Docker images and test on them so that new users can straight away use the image. Really practical with not much extra work I guess. What is your opinion?

**Comment by MakisH** [comment]
Thank you very much for sharing this, ykhedar! :D Yes, this is a great idea and we are working on this already, alongside tests of every kind. Indeed, Ubuntu 16.10 offers a newer Boost version, which simplifies the building process a lot.

A small side-comment: keep in mind that the links of the form `khedar@bitbucket.com` trigger warnings when other users try to visit your repositories. I changed your link to `https://bitbucket.org/khedar/`. You can always test such things easily in a private window! ;)

Feel free to continue giving us feedback! It is valuable!

**Comment by uekerman** [comment]
Just as an add-on. Currently a student of @floli works on docker containers for preCICE, but also for coupled codes. His name is Jakob - I don't have his GitHub contact. Maybe, @floli, you can reference him here? The main reason for docker containers for us at the moment is to develop complete coupled test scenarios and use them as weekly (not decided yet) regression tests. 
@MakisH also works on other "binary" possibilities, debian packages etc.

**Comment by MakisH** [comment]
We now have several Dockerfiles in our [systemtests]() repository. For example, [here is a system test for the heated plate tutorial](https://github.com/precice/systemtests/tree/master/Test_of-of.Ubuntu1604), as well as for the [heat exchanger](https://github.com/precice/systemtests/tree/master/Test_of-ccx.Ubuntu1604).

I understand that the need is to have a quick & easy way to try out preCICE. We are working on such ways, as well as binary packages. This would cover then more than the OpenFOAM adapter. Therefore, I am closing this issue.
