### ISSUE TITLE
Support formatting

### ISSUE THREAD

**Issue by DavidSCN** [precice/openfoam-adapter#126]
The adapter follows the [openfoam coding style](https://openfoam.org/dev/coding-style-guide/). Unfortunately, there is no formatting file available and it is hard to check for contributors.

It would be much easier for other people to contribute, if we support any formatting and the code would be formatted consistently.

**Comment by MakisH** [comment]
Good point! I opened an upstream [issue in the OpenFOAM GitLab](https://develop.openfoam.com/Development/openfoam/issues/1634). Maybe there is something already (I could not find anything). If not, let's create one. I would be interested in trying this, but you can also have a look if you want.

I would like to avoid using a completely different style, so let's see if we can merge our efforts.

**Comment by MakisH** [comment]
I will have a look on this and try to solve it upstream. But it may take a while.
