### ISSUE TITLE
CHT: Radiative heat flux portion does not considered.

### ISSUE THREAD

**Issue by TEFEdotCC** [precice/openfoam-adapter#140]
When a fixed temperature condition is applied at the wall, the heat flux to the wall from a fluid cell is computed as
<img src="https://render.githubusercontent.com/render/math?math=q - q_{rad}=+ h_f \cdot ( T_w - T_f )">

<img src="https://render.githubusercontent.com/render/math?math=h_f"> : fluid-side local heat transfer coefficient
<img src="https://render.githubusercontent.com/render/math?math=T_w"> : wall surface temperature
<img src="https://render.githubusercontent.com/render/math?math=T_f"> : local fluid temperature
<img src="https://render.githubusercontent.com/render/math?math=q_{rad}"> : radiative heat flux

At the moment the CHT modules does not respect the radiative heat flux.

**Comment by TEFEdotCC** [comment]
Usage of *externalWallHeatFluxTemperature* (in constantHeatFlux mode) insteady of fixedGradient in T field at wall patch should solve the problem.

https://develop.openfoam.com/Development/openfoam/-/tree/master/src/TurbulenceModels/compressible/turbulentFluidThermoModels/derivedFvPatchFields/externalWallHeatFluxTemperature

**Comment by MakisH** [comment]
Thank you very much for the hints, @TEFEdotCC! With a quick look, this seems to be related to #12, correct? If yes, we can also continue the discussion there.

**Comment by TEFEdotCC** [comment]
Upps and yes, #12  is the same topic. Ok, close this and move the discussion there.
