### ISSUE TITLE
Blender not run in ubuntu terminal to use OpenFoam

### ISSUE THREAD

**Issue by Prem1110** [precice/openfoam-adapter#141]
![Screenshot 2020-09-20 023623](https://user-images.githubusercontent.com/71584471/93706279-3a8f9100-faea-11ea-9964-12c876dde1c2.jpg)

This is the issue with running the blender I don't know how to solve this I am new to coding and learning OPenFoam.

**Comment by MakisH** [comment]
Hi @Prem1110,

thank you very much for opening an issue, but, if I understand correctly, this has nothing to do with the OpenFOAM adapter for preCICE, or with OpenFOAM itself and I have no idea how to help you with that.

Probably you will have better chances if you ask the [Blender community](https://www.blender.org/community/). Good luck! :-)
