### ISSUE TITLE
Get additional time directories with "no data"

### ISSUE THREAD

**Issue by TEFEdotCC** [precice/openfoam-adapter#145]
preCICE version: 2.1.0
OpenFOAM verison: v2006 with fixes

It occurs in both examples of https://github.com/TEFEdotCC/openfoam-adapter/tree/CHT_WallHeatFlux/examples/CHT

**precice-config.xml**
```
<time-window-size value="0.001" method="fixed" />
```

**controlDict**
```
writeControl    adjustable;
writeInterval   0.04;
```

Which directories I get
```
0.39
 - uniform/functionObjects/functionObjectProperties
0.4
 - uniform/functionObjects/functionObjectProperties
 - uniform/time
 - DT
 - flux
 - T
 - ...
0.79
 - uniform/functionObjects/functionObjectProperties
0.8
 - uniform/functionObjects/functionObjectProperties
 - uniform/time
 - DT
 - flux
 - T
 - ...
0.119
 - uniform/functionObjects/functionObjectProperties
0.12
 - uniform/functionObjects/functionObjectProperties
 - uniform/time
 - DT
 - flux
 - T
 - ...
```
Why I get the directories `writeInterval - time-window-size`? What I do wrong?

**Comment by TEFEdotCC** [comment]
`runTime` and `adjustableRunTime` does also not fix the problem.

**Comment by MakisH** [comment]
This is a known issue affecting (and originating from) some openfoam.com versions: https://github.com/precice/openfoam-adapter/issues/26

In some tutorials in the `precice/tutorials` repository (e.g. `flap_perp/OpenFOAM-CalculiX`) you can find a script `removeObsoleteFolders.sh` to clean these up.

**Comment by TEFEdotCC** [comment]
Thanks for the advice.
Creating a script to clean up is fine, but solve not so problem.

Ok. It is a openfoam.com problem. But I'm not sure it could be prevented. I do that on my personal list. I had it to solve the affects, I like it to solve the problem. (I hope I translate it correctly with my bad english :-) )

**Comment by MakisH** [comment]
I would also really like to solve the problem, but this can only be solved upstream. :-) I have not opened an issue, but maybe I should (even though our use case is rather exotic).
