### ISSUE TITLE
fixedFluxPressure boundary fails

### ISSUE THREAD

**Issue by jaydeshpande** [precice/openfoam-adapter#15]
[https://1drv.ms/u/s!AvEMDnpUbHI2ggCtaUp6pvMLnj5O
](url)
In the above case - change p_rgh wall boundary from zeroGradient to fixedFluxPressure. 

ONLY when run through PreCICE - it throws following error:
`updateCoeffs(const scalarField& snGradp) MUST be called before updateCoeffs() or evaluate() to set the boundary gradient.
`

Simply running buoyantPimpleFoam works.

**Comment by jaydeshpande** [comment]
Patch - 

Noticed that it evaluates the boundary again at preciceAdapter::Adapter::readCheckpoint()

modified the evaluateBoundaries_ similar to epsilon : 
```
                if ("p_rgh" != volScalarFields_.at(i)->name())
                {
                    volScalarFields_.at(i)->correctBoundaryConditions();
                }
```

**Comment by MakisH** [comment]
Thank you very much for the bug report. Looks similar to #4 and it is useful to find more cases where this happens. I leave it open for now, until we find the root cause of the problem.
