### ISSUE TITLE
Assert the correct layer of 2D computations

### ISSUE THREAD

**Issue by DavidSCN** [precice/openfoam-adapter#154]
https://github.com/precice/openfoam-adapter/blob/8355e96ff1c9721d45c42f8d79c8e9da22425d76/Interface.C#L94-L105

We implicitly assume here that the out-of-plane layer is the z-axis and the interface is located in xy-plane. We currently don't do anything if the user violate it, but the result will be nonsense. In other places, we perform a loop over `dim` resulting in a similar problem. We need to prevent this case. Also related to precice/calculix-adapter#56.

**Comment by MakisH** [comment]
I see two options for this:

1. Ask the user which out-of-plane dimension to use.
2. Automatically derive this in the beginning, based on the number of cells per dimension (not sure how easy that would be, but probably relatively easy).

I guess that option 2 should be reasonable enough.

**Comment by DavidSCN** [comment]
I think the easiest option would be to check the value of the z-coordinates. We can only have two distinct values here, everything else should be wrong and it should be easy to check. So this would be the solution for option two.

**Comment by MakisH** [comment]
Fixed in #155 (currently on develop), closing already.
