### ISSUE TITLE
Need a release workflow

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#178]
We closed #170 with the argument that we can just have a reminder in our release workflow to update the branches (with simple merging, to not get too many trivial pull requests).

In this release workflow we would need notes to:

- [ ] Bump the version message n in `Adapter.C`
- [ ] Merge the changelog entries
- [ ] Prepare release notes
- [ ] Check the documentation for any missing updates
- [ ] Merge PR of `develop` to `master` (simple merge, not squash & merge)
- [ ] Merge `master` back to `develop` and change the version message.
- [ ] Update the version-specific OpenFOAM branches

What else would we need?

We could make this a PR template, but in our experience with precice/precice, GitHub does not let you select the template when you open a pull request. Instead, we could add this as a Markdown file in `tools/`.

**Comment by DavidSCN** [comment]
Yes, I don't like the PR templates so much. I would also suggest to go with the (rather simple) idea of a checklist. Merging to master (for releasing) requires without utilizing any specific root permissions anyway an approval, so we should be able to go through the list.

**Comment by MakisH** [comment]
Temporary documentation: I cleaned up the version-specific branches and we currently have:

```
master <-- OpenFOAM4 <-- OpenFOAM5 <-- OpenFOAM6 <-- OpenFOAM7 <-- OpenFOAMdev
                  ^-- OpenFOAMv1806                    ^-- fix-129 (OpenFOAM8)
```

Currently, `OpenFOAM4`, `OpenFOAM5`, `OpenFOAMv1806` all point to the same state. I have not tried how much older ESI versions we currently support.

Each branch adds one commit, so rebasing is now very easy (maybe apart from OpenFOAM8). After every update of OpenFOAM4, we need to rebase for `push --force` all other branches again.
