### ISSUE TITLE
Compatibility with pimpleDyMFoam

### ISSUE THREAD

**Issue by strootg** [precice/openfoam-adapter#19]
Hello,

Is there any planned update to the FSI portion of the adapter? Specifically, are plans made to couple the pimpleDyMFoam solver with a FSI solver?

If not, would you be able to provide any information or documentation you may have on the process that one should take?

**Comment by MakisH** [comment]
Hello,

yes, this is work in progress, which is planned to finish soon-ish. There is a [issue on that](https://github.com/precice/openfoam-adapter/issues/7), let's continue the discussion there. :-)
