### ISSUE TITLE
Missing exit message in `Allwmake`

### ISSUE THREAD

**Issue by DavidSCN** [precice/openfoam-adapter#190]
Due to the immediate exit
https://github.com/precice/openfoam-adapter/blob/a5c01a0993c34787c146c70368dd01cec37673e0/Allwmake#L2
 the `Allwmake` script 'exits' as follows:

```
Building the OpenFOAM-preCICE adapter...
```
in case the pkg-config is not discoverable. There is actually a message missing, which tells the user what went wrong.

**Comment by MakisH** [comment]
Good catch, I can take care of this.
