### ISSUE TITLE
Precice 2.2.1 and OF 2106: flow-over-heated-plate: error

### ISSUE THREAD

**Issue by Mak57** [precice/openfoam-adapter#193]
Please provide the following information:
- Adapter version/commit number/last download:
- OpenFOAM version: 2106
- preCICE version: 2.1.1
- Attach the adapter building files `allwmake.log`, `ldd.log`, as well as any logs that could be helpful.

**Comment by DavidSCN** [comment]
Hi @Mak57,
we happily offer support on our [discourse](https://precice.discourse.group/) channel. Please open up a thread and describe your problem there in detail. Thanks!
