### ISSUE TITLE
Compatibility with OpenFOAM 9

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#200]
This is a meta-issue for the compatibility updates needed for OpenFOAM 9.

As is now the norm, OpenFOAM 9 does not build with the branch for OpenFOAM 8 (which does not build with the one for OpenFOAM 7, etc). For this reason, we are currently focusing on the OpenFOAM.com versions, which offer us some stability for a wide range of versions.

OpenFOAM 9 release notes: https://openfoam.org/release/9/

First building issue (starting from the `OpenFOAM8`/`OpenFOAMdev` branch:

```
Interface.C:3:10: fatal error: faceTriangulation.H: No such file or directory
    3 | #include "faceTriangulation.H"
      |          ^~~~~~~~~~~~~~~~~~~~~
```

Any community contributions are particularly welcome here.

**Comment by engenegr** [comment]
Hey. I did this in separate adapter. Added volume coupling as a bonus. Not really tested it, only one run with a tutorial specifically designed for Temperature coupling across whole domain and boundary conditions. Supports only identical meshes so it is 1:1 now. I won't develop mappings of other types since I do not need them.

https://github.com/engenegr/openfoam-org-adapter/

**Comment by epitomeri** [comment]
@engenegr

Hello Ilya,

I have attempted to build your OF adapter (https://github.com/engenegr/openfoam-org-adapter/) with OpenFOAM-9 and preCICE 2.3.0 and still encountered the fatal error "Interface.C:3:10: fatal error: faceTriangulation.H: No such file or directory". I could not locate this header anywhere in the OpenFOAM-9 branch. Could you please let me know what you did to overcome this issue, if at all?

Thanks in advance,
Satish

**Comment by epitomeri** [comment]
@engenegr

Hello Ilya,

I have attempted to build your OF adapter (https://github.com/engenegr/openfoam-org-adapter/) with OpenFOAM-9 and preCICE 2.3.0 and still encountered the fatal error "Interface.C:3:10: fatal error: faceTriangulation.H: No such file or directory". I could not locate this header anywhere in the OpenFOAM-9 branch. Could you please let me know what you did to overcome this issue, if at all?

Thanks in advance,
Satish

**Comment by engenegr** [comment]
@epitomeri 

thank you for your interest. It seems in `9` version `faceTriangulation` was eliminated and replaced with `polygonTriangulation`.

https://github.com/OpenFOAM/OpenFOAM-9/commit/02b97a714a17e066e3918e2fd87cde21aedf6ced

Likely i will need to do relevant work in org-adapter but it will be later. So I am sorry I have no ready solution now.

**Comment by MakisH** [comment]
See branch https://github.com/precice/openfoam-adapter/tree/OpenFOAM9 and the `_OpenFOAM9` archive in our [releases](https://github.com/precice/openfoam-adapter/releases) for a compatible version.
