### ISSUE TITLE
Coupling data jump in restarted FSI simulation

### ISSUE THREAD

**Issue by davidscn** [precice/openfoam-adapter#223]
Please provide the following information:
- Adapter version: v1.1.0
- OpenFOAM version: OpenFOAM 2012
- preCICE version: v2.3.0

I'm currently experimenting with restart functionalities by simulating two seconds of our perpendicular flap tutorial and restarting it again: first I simulate the complete two seconds as a reference and exporting the vtks, afterwards, I simulate the first second and restart it later on using the replay mode of aste on the solid side. Looking at the `Stress` data results in the following 
   
![](https://user-images.githubusercontent.com/33414590/157642771-b60f6292-1e4e-43df-81d1-feba663822b7.png)

There is an unreasonable jump at the watchpoint I don't understand. Restarting the same simulation using a real (the solid) participant results in a different simulation.

**Comment by DavidSCN** [comment]
First important issue is that the reference configuration changes when using a restart mechanism, i.e., we use the current ('deformed') mesh and vertices in order to define the coupling interface.

**Comment by DavidSCN** [comment]
I have a fix. @MakisH I guess this would be worth a bugfix release.

**Comment by MakisH** [comment]
> 

Yes, please prepare a PR. We could then include #220 in that.
