### ISSUE TITLE
Missing compatibility with RBFMeshMotionSolver

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#227]
solids4Foam offers the mesh motion solver [RBFMeshMotionSolver](https://bitbucket.org/philip_cardiff/solids4foam-release/src/master/src/solids4FoamModels/fluidModels/finiteVolume/RBFMeshMotionSolver/RBFMeshMotionSolver.H), which would be a good alternative to the displacementLaplacian (the solver all of our tutorials are using). However, when configuring a simulation with pimpleFoam and this mesh motion solver (@CCaccia73), it complains that it cannot find the field `displacementLaplacian`. Furthermore, no fields of type `pointVectorField` are shown to be available in the region `0()`.

@CCaccia73 please attach the respective log / case files to reproduce the problem. Consider OpenFOAM/solids4Foam newbies and better base it on a tutorial. 😇

**Comment by AndresPedemonteFIUBA** [comment]
This would indeed be a very interesting feature. A while back I asked Dr. Cardiff, solids4Foam's principal developer, if that solver could be used in OF v7. He answered:
> Currently the RBFMeshMotionSolver classes are also compiled with OF7 so it should be possible to use them, but please check.

I briefly tried to do so but was not able to succesfully run a case with it. I always got an error message along the lines of "could not find RBFMeshMotionSolver" even though s4f compiled succesfully and I was including the (I believe) correct libraries for it. I'd be very interested in how @Ccaccia73 was able to at least make FOAM accept and "find" that motion solver (and version used. org-FOAM? ESI-FOAM?).

Also, I think this issue is closely related to, if not the same as, #85.

**Comment by Ccaccia73** [comment]
Hi, first I extracted the RBFMeshMotionSolver from solids-4-foam and compiled it for v21.06. The Repo is here: https://gitlab.com/stilita/myRBFMeshMotionSolver. Then I simply substituted the dynamicMeshDict file in the verttical flap tutorial with the one here:

 `
dynamicFvMesh dynamicMotionSolverFvMesh;

motionSolverLibs ("libRBFMeshMotionSolver.so");
motionSolver RBFMeshMotionSolver;

                                                                                        
staticPatches ( frontAndBack );
movingPatches ( flap );
fixedPatches  ( inlet outlet upperWall lowerWall );

interpolation
{
    function     TPS;
}

coarsening
{
    enabled      no;
    tol          0.001;
    minPoints    3;
    maxPoints    100;
    livePointSelection yes;
    exportSelectedPoints yes;
    tolLivePointSelection 0.1;
}

polynomial       true;                      
cpu                     true;
fullCPU              true;
`
And came into the problem mentioned by @MakisH, where I'm stuck at the moment. Hopefully this should allow to reproduce the issue.

**Comment by AndresPedemonteFIUBA** [comment]
>  it complains that it cannot find the field `displacementLaplacian`. Furthermore, no fields of type `pointVectorField` are shown to be available in the region `0()`.

Quick question: could it be that was a typo and the intended meaning was that it couldn't find the field `pointDisplacement`? I checked the solids4Foam tutorials and it [looks like](https://bitbucket.org/philip_cardiff/solids4foam-release/src/master/tutorials/fluidSolidInteraction/beamInCrossFlow/linearGeometryElasticBeam/) the RBFMeshMotion solver uses the pointVectorField `pointMotionU` (or the tetPointVectorField `motionU` for the Foundation version) instead of `pointDisplacement`.  

Does the adapter support handling those fields instead of `pointDisplacement`?

**Comment by MakisH** [comment]
> > it complains that it cannot find the field `displacementLaplacian`. Furthermore, no fields of type `pointVectorField` are shown to be available in the region `0()`.
> 
> Quick question: could it be that was a typo and the intended meaning was that it couldn't find the field `pointDisplacement`? 

I wrote this issue while looking at @Ccaccia73's screen, so it can be indeed a typo. @Ccaccia73 please confirm.

> I checked the solids4Foam tutorials and it [looks like](https://bitbucket.org/philip_cardiff/solids4foam-release/src/master/tutorials/fluidSolidInteraction/beamInCrossFlow/linearGeometryElasticBeam/) the RBFMeshMotion solver uses the pointVectorField `pointMotionU` (or the tetPointVectorField `motionU` for the Foundation version) instead of `pointDisplacement`.

This is very helpful, thanks!

> Does the adapter support handling those fields instead of `pointDisplacement`?

You can generally set a different name for [`pointDisplacement`](https://github.com/precice/openfoam-adapter/blob/17d1776a31f96958c5629d0af948675028667f9b/FSI/FSI.C#L61). This is currently not documented for the FSI module config, but here is the documentation for the CHT module: https://precice.org/adapter-openfoam-config.html

But just changing the name does not mean that the requested field will be supported. One can only try.

**Comment by Ccaccia73** [comment]
Hi,
the error message is:
`
--> FOAM FATAL ERROR:
    request for pointVectorField pointDisplacement from objectRegistry region0 failed
    available objects of type pointVectorField are
0()
`
It seems that RBF doesn't populate pointDisplacement. It is also a little bit hard for me to test RBF alone: I only see a couple of cases: **movingBlockRBF** in foam-extend 4.1, which works, at least to some point to me. The other one is in solids-4-foam which is commented out. Maybe the first step is to find working examples of RBF. I have also received a suggestion about using a different dynamicMeshDict, like this one, but it doesn't work:
`
dynamicFvMesh dynamicMotionSolverListFvMesh;

solvers
{

	deformation
	{
		motionSolverLibs (fvMotionSolvers);
		motionSolver displacementLaplacian;
		diffusivity uniform;
	}	
		
	RBF
	{
		motionSolverLibs ("libRBFMeshMotionSolver.so");
		motionSolver RBFMeshMotionSolver;
                                                                                         
		staticPatches ( upperWall  back lowerWall front);
		movingPatches ( flapBaffle_master flapBaffle_slave );
		fixedPatches  ( inlet inletWater outlet );
		interpolation
		{
			function     TPS;
		}
		coarsening
		{
			enabled      no;
			tol          0.001;
			minPoints    3;
			maxPoints    100;
			livePointSelection yes;
			exportSelectedPoints yes;
			tolLivePointSelection 0.1;
        }

        polynomial       true;		
		cpu              true;
		fullCPU          true;
		
	}
};
`

**Comment by solids4foam** [comment]
Hi all,

See https://github.com/precice/openfoam-adapter/pull/241.

Philip

**Comment by NUGUY2022** [comment]
Hi,
Does RBFMeshMotionSolver support interFoam? I tested it with interFoam and it failed. Any advice about employing it in interFoam?

**Comment by MakisH** [comment]
> Hi, Does RBFMeshMotionSolver support interFoam? I tested it with interFoam and it failed. Any advice about employing it in interFoam?

I have no idea, but I guess this is not directly related with the preCICE adapter. A better place to ask would be in the solids4foam issue tracker: https://github.com/solids4foam/solids4foam/issues

Code: https://github.com/solids4foam/solids4foam/tree/master/src/RBFMeshMotionSolver
