### ISSUE TITLE
How to using another Functions during simulation with PreCICE?

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [precice/openfoam-adapter#243]
I am Thanh.
now I am using OpenFoam version 8.0, Adapter version: OpenFoam adapter v11.0 OpenFoam v8.0, and PrCICE version 1.0.

in my simulation need to calculate the mean velocity, So I have to use the average function in OpenFoam but PreciceAdapter notice that only preCICE will work. do you know how to trigger other functions in the Openfoam like that?

ThanK you

**Comment by MakisH** [comment]
Hi @nguyenhoaiThanhbk2811,

as I also wrote on the [forum](https://precice.discourse.group/t/how-to-use-other-functions-during-simulation-with-precice/1149/3), you can just specify additional function objects before the adapter in your `controlDict` and this should work. I added a note in the [documentation](https://precice.org/adapter-openfoam-config.html).

In case your specific case does not work, please include more details in the forum. I am closing this for now, will reopen if needed.
