### ISSUE TITLE
Continutity error cannot be removed by adjusting the outflow

### ISSUE THREAD

**Issue by nguyenhoaiThanhbk2811** [precice/openfoam-adapter#249]
now I am simulating for Fluid-Fluid coupling. I get the error 
" -> FOAM FATAL ERROR: 
Continuity error cannot be removed by adjusting the outflow.
Please check the velocity boundary conditions and/or run potentialFoam to initialise the outflow.
Total flux: 7.8e-5
Specified mass inflow: 3.5e-8
Specified mass outflow  : 1.9e-8
Adjustable mass outflow : 0
"

At the interface, I want to transfer velocity and gradient velocity to each other. 

Could you give me some advice to fix the problem?

Thank you!

**Comment by MakisH** [comment]
Related discussion: https://precice.discourse.group/t/continuity-error-cannot-be-removed-by-adjusting-the-outflow/1162

Let's continue there and reopen if this turns out to be a bug in the adapter.

**Comment by GJ-A** [comment]
Hi nguyenhoaiThanhbk2811 ,
Have you fix it out? I get the same problem. seeking for some help.
Thank u
