### ISSUE TITLE
Temperature in Fluid-Fluid coupling

### ISSUE THREAD

**Issue by thesamriel** [precice/openfoam-adapter#272]
### Coupling Temperature

Temperature coupling can be added to the Fluid-Fluid module by a Dirichlet-Neumann coupling by adding ```couplingDataUser``` classes for Temperature and TemperatureGradient. These are just copies of the respective pressure classes, only changing p to T.

The simplification from [HeatFlux](https://github.com/precice/openfoam-adapter/blob/develop/CHT/HeatFlux.H) to TemperatureGradient (as opposed to the CHT module) is due to the assumption that $\kappa_f$ is the same on both sides of the fluid-fluid coupling interface:

$$Q_1 = \kappa_f * \nabla T_1 = \kappa_f * \nabla T_2 = Q_2$$

$$ \nabla T_1 =  \nabla T_2 $$

$Q_i$ is the heat flux on either side of the interface.

Test case with flow over a heated pipe segment using ```buoyantPimpleFoam``` shows very good results: (Top monolithic, bottom coupled)

![image](https://user-images.githubusercontent.com/43962524/216290632-32bd03c0-1b48-487f-814a-663ab6668a75.png)

![heat_downstream_plus](https://user-images.githubusercontent.com/43962524/216291398-894b7b3b-df87-4c30-add1-307d89c3c469.png)

**Comment by MakisH** [comment]
Adding `Temperature` and `TemperatureGradient` (with the naming considerations discussed in #276) in the FF module sounds like something we should anyway do at this point, which should also be rather easy.

**Comment by MakisH** [comment]
Closed by #281.
