### ISSUE TITLE
Custom Inlet-Outlet Boundary conditions for fluid-fluid coupling

### ISSUE THREAD

**Issue by thesamriel** [precice/openfoam-adapter#274]
The flow direction at the fluid-fluid coupling interface might not stay constant over the course of the simulation.
Therefore, it is useful to use inlet-outlet boundary conditions that switch their behavior according to the flow direction.

The [inletOutlet](https://www.openfoam.com/documentation/guides/latest/api/classFoam_1_1inletOutletFvPatchField.html#details) and [outletInlet](https://www.openfoam.com/documentation/guides/latest/api/classFoam_1_1outletInletFvPatchField.html#details) conditions work with `zeroGradient` and `fixedValue` behaviors.

In my [thesis](https://mediatum.ub.tum.de/node?id=1696254&change_language=en) I showed that we achieve better results by using e.g. `fixedFluxExtrapolatedPressure` instead of a pressure gradient condition. To implement this behavior in an inlet-outlet boundary condition, we need to provide custom boundary conditions.
These can be compiled with the adapter and then be used as the boundary conditions at the coupling boundaries. I would recommend them to users, since they can be set on both sides on the interface.

We also need to adjust the `write()` and `read()` methods for the affected variables to work with theses new boundary conditions.

**Comment by thesamriel** [comment]
I forgot, we already had an issue for this, namely #232

**Comment by thesamriel** [comment]
Okay perfect.

The FF module still supports the basic boundary conditions and users can also derive their BC from our provided ones.

**Comment by MakisH** [comment]
Fixed by https://github.com/precice/openfoam-adapter/pull/281

Find new boundary conditions in https://github.com/precice/openfoam-adapter/tree/develop/FF/BoundaryConditions
