### ISSUE TITLE
First read data is zero

### ISSUE THREAD

**Issue by thesamriel** [precice/openfoam-adapter#275]
### Problem
The preCICE OpenFOAM Adapter is calling the `configure()` function for initialization of the preCICE adapter function object. In this function the adapter makes a call to [`readCouplingData()`](https://github.com/precice/openfoam-adapter/blob/efbe339a10c162ac3d03c2706db1ed5c3edd0257/Adapter.C#L349) without a call to  `writeCouplingData()` beforehand.

This implies that the first participant reads the coupling data from a buffer that has not been filled before. Since the buffer seems to be initialized to zero, all read coupled values are set to zero, overwriting the user-given initial boundary condition at the coupling interface.

This became problematic when I tried fluid-fluid coupling with the buoyantPimpleFoam solver. Pressure is set to absolute values of 0 at the coupling interface, which crashes the simulation at the first timestep.

### Solution idea
I was thinking about wrapping the call to [`readCouplingData()`](https://github.com/precice/openfoam-adapter/blob/efbe339a10c162ac3d03c2706db1ed5c3edd0257/Adapter.C#L349) in a check that checks the coupling scheme and whether it is the first participant, but I am not sure if this information is available from that place.

If this is the only problematic edge case, I could also make an exception for pressure reading only inside the FF module.

**Comment by MakisH** [comment]
If this is true, we should definitely fix it. But it looks like we have already handled it correctly. Had you enabled initializing data in the `precice-config.xml`?

Note that this should happen when the coupling partner is also OpenFOAM.

> ### Solution idea
> 
> I was thinking about wrapping the call to [`readCouplingData()`](https://github.com/precice/openfoam-adapter/blob/efbe339a10c162ac3d03c2706db1ed5c3edd0257/Adapter.C#L349) in a check that checks the coupling scheme and whether it is the first participant, but I am not sure if this information is available from that place.

We should actually just check if we need to write initial data and then write: https://precice.org/couple-your-code-initializing-coupling-data.html

This is also what we already do:

https://github.com/precice/openfoam-adapter/blob/master/Adapter.C#L540-L548

This is called inside `initialize()`, which is called inside `configure()`, before calling the first `readCouplingData()`.

**Comment by thesamriel** [comment]
Indeed this is handled when using the xml tag `initialize="yes"` for `Pressure`.
I didn't realize this option exists, thanks for clarifying!
