### ISSUE TITLE
Interface.C faceCenters triggers Wmaybe-uninitialized

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#28]
Issue reported by @DavidSCN.

https://github.com/precice/openfoam-adapter/blob/c0f28814c4d8da073a73cd076dc4e1dfd5da7e74/Interface.C#L75-L85

The above part of `Interface.C` returns the following warning in some compilers:

```
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam5/src/finiteVolume/lnInclude -I/opt/openfoam5/src/meshTools/lnInclude -I/opt/openfoam5/src/transportModels/ -I/opt/openfoam5/src/transportModels/compressible/lnInclude -I/opt/openfoam5/src/thermophysicalModels/basic/lnInclude -I/opt/openfoam5/src/TurbulenceModels/turbulenceModels/lnInclude -I/opt/openfoam5/src/TurbulenceModels/compressible/lnInclude -I/opt/openfoam5/src/TurbulenceModels/incompressible/lnInclude -I/usr/include/yaml-cpp -I/usr/include/eigen3  -I/home/imperator/precice/src/precice -I../ -DADAPTER_DEBUG_MODE -IlnInclude -I. -I/opt/openfoam5/src/OpenFOAM/lnInclude -I/opt/openfoam5/src/OSspecific/POSIX/lnInclude   -fPIC -c CHT/KappaEffective.C -o Make/linux64GccDPInt32Opt/CHT/KappaEffective.o
Interface.C: In member function ‘void preciceAdapter::Interface::configureMesh(const Foam::fvMesh&)’:
Interface.C:83:49: warning: ‘*((void*)&<anonymous> +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             for (int i = 0; i < faceCenters.size(); i++)
                                 ~~~~~~~~~~~~~~~~^~
Interface.C:85:58: warning: ‘*((void*)&<anonymous> +16)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
                 vertices[verticesIndex++] = faceCenters[i].x();
                                                          ^
```

I cannot reproduce this with g++ 5.4.0 (Ubuntu 16.04). The above is probably with g++ 7.3.0 / Ubuntu 18.04 (please, @DavidSCN, correct me if I am wrong).

[This StackOverflow question](https://stackoverflow.com/questions/14132898/gcc-wuninitialized-wmaybe-uninitialized-issues#14132910) may be helpful.

**Comment by ChrisiMW** [comment]
Got similar warnings building the adapter:

g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam5/src/finiteVolume/lnInclude -I/opt/openfoam5/src/meshTools/lnInclude -I/opt/openfoam5/src/transportModels/ -I/opt/openfoam5/src/transportModels/compressible/lnInclude -I/opt/openfoam5/src/thermophysicalModels/basic/lnInclude -I/opt/openfoam5/src/TurbulenceModels/turbulenceModels/lnInclude -I/opt/openfoam5/src/TurbulenceModels/compressible/lnInclude -I/opt/openfoam5/src/TurbulenceModels/incompressible/lnInclude -I/home/chrisi/yaml-cpp-yaml-cpp-0.5.3/include -I/usr/include/eigen3  -I/home/chrisi/precice-1.1.1//src/precice  -I../ -DADAPTER_DEBUG_MODE -IlnInclude -I. -I/opt/openfoam5/src/OpenFOAM/lnInclude -I/opt/openfoam5/src/OSspecific/POSIX/lnInclude   -fPIC -c Interface.C -o Make/linux64GccDPInt32Opt/Interface.o
Interface.C: In member function ‘void preciceAdapter::Interface::configureMesh(const Foam::fvMesh&)’:
Interface.C:80:45: warning: ‘*((void*)&<anonymous> +8)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         for (int i = 0; i < faceCenters.size(); i++)
                             ~~~~~~~~~~~~~~~~^~
Interface.C:82:54: warning: ‘*((void*)&<anonymous> +16)’ may be used uninitialized in this function [-Wmaybe-uninitialized]
             vertices[verticesIndex++] = faceCenters[i].x();

I‘m using ubuntu 18.04 and gcc version 7.3.0.
