### ISSUE TITLE
OpenFOAM2.4.0-MNF and XDEM coupling

### ISSUE THREAD

**Issue by MadanBK1** [precice/openfoam-adapter#336]
Hello preCICE Community,

I am currently working with OpenFOAM2.4.0-MNF and utilizing the dsmcFoamPlus solver. I am interested in coupling this solver with XDEM and would like to know if this is feasible using the existing OpenFOAM preCICE adapter.

From what I have gathered, the preCICE adapter supports a range of coupled simulations including fluid-structure interaction (FSI), conjugate heat transfer (CHT), and fluid-fluid (FF) simulations​ ([preCICE.org](https://precice.org/adapter-openfoam-support))​​ ([preCICE.org](https://precice.org/adapter-openfoam-overview))​. However, I am unsure about the specific steps or modifications required to achieve the coupling with XDEM, especially given the specialized nature of the dsmcFoamPlus solver.

Has anyone in the community successfully coupled OpenFOAM solvers with XDEM using preCICE? If so, could you please share your experiences or point me toward relevant documentation or examples? Additionally, any advice on configuring the preCICE adapter for this specific use case would be greatly appreciated.

Thank you for your support!

Best regards,
Madan B K

**Comment by MakisH** [comment]
Please post such questions in the forum (I see you already opened one): https://precice.discourse.group/t/openfoam2-4-0-mnf-and-xdem-coupling/1995
