### ISSUE TITLE
ADAPTER_PKG_CONFIG_CFLAGS

### ISSUE THREAD

**Issue by charithaRdissanayaka** [precice/openfoam-adapter#340]
Hello Sir,

I tried to compile openfoam-adapter for the OpenFOAM6. 
but it is giving the following error.
Please help me to solve this.

I use Ubuntu 22.04 WSL.

make: *** [/home/yachiyo/OpenFOAM/OpenFOAM-6/wmake/rules/General/transform:26: Make/linux64GccDPInt64Opt/Interface.o] Error 1
=== ERROR: Building failed. See wmake.log for more. ===
Possible causes:
- Make sure you are using a compatible version of the adapter for your OpenFOAM version:
  https://precice.org/adapter-openfoam-support.html
- Is preCICE discoverable at compile time? Check the content of ADAPTER_PKG_CONFIG_CFLAGS above.
Attach your Allwmake.log and wmake.log when asking for help.

**Comment by MakisH** [comment]
Hi @charithaRdissanayaka,

looks like this is a user support request. For such, please use the preCICE forum: https://precice.discourse.group/ We use GitHub issues only for confirmed bugs and feature requests.

The adapter is currently (temporarily) not supporting OpenFOAM6, but we are discussing solutions in #328.

**Comment by charithaRdissanayaka** [comment]
> Hi @charithaRdissanayaka,
> 
> looks like this is a user support request. For such, please use the preCICE forum: https://precice.discourse.group/ We use GitHub issues only for confirmed bugs and feature requests.
> 
> The adapter is currently (temporarily) not supporting OpenFOAM6, but we are discussing solutions in #328.

@MakisH 

Hello Sir,

Thank you very much for your reply. I will check the issue in the user support forum.

**Comment by charithaRdissanayaka** [comment]
@MakisH 

Hello sir,

Can you explain me or provide me a weblink to compile preCICE for openfoam6 with calculix-adapter and openfoam-adapter.

I am getting stuck at my case study works.
I tried to find a solution, but I could not.

**Comment by MakisH** [comment]
@charithaRdissanayaka this is currently not straight-forward, you need to wait a bit more till we release a recent variant of the adapter compatible with OpenFOAM 6.

In the meantime, you can have this with preCICE v2, using an older version: https://github.com/precice/openfoam-adapter/releases/tag/v1.2.3

You will then need the versions described in the preCICE Distribution v2211: https://precice.org/installation-distribution.html#v22110

I will (hopefully) update this issue once the org-compatible variants are ready for preCICE v3.
