### ISSUE TITLE
adapter for the openFoam6.

### ISSUE THREAD

**Issue by charithaRdissanayaka** [precice/openfoam-adapter#341]
Do anyone can provide me a solution to install the preCICE adapter for the OpenFOAM6 in Ubuntu22.04.
I successfully installed the OpenFOAM6 in Ubuntu 22.04 with Third-Party folder.

But I could not install the openfoam-adapter for the OpenFOAM6.

I need to do some simulations by using 2dto3d coupling of SWE and OpenFOAM.

your kind help is highly appreciated.

**Comment by MakisH** [comment]
I am not sure if you have already seen my replies in your previous issue regarding this: https://github.com/precice/openfoam-adapter/issues/340

Please read those before opening any new issues.
