### ISSUE TITLE
FSI: Add an option for stress mapping

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#41]
At the moment, we map forces. However, it would be very nice to also be able to map stresses, which would be easy to implement, having already implemented `Force.C`.

A limitation here is that we cannot use stresses in CalculiX at the moment. So, a prerequisite for this would be to either:

A. Implement stresses reading also in the [calculix-adapter](https://github.com/precice/calculix-adapter),
B. Add connectivity information in the openfoam-adapter, so that we use a [preCICE action](https://github.com/precice/precice/wiki/Actions-Configuration) to convert the stresses to forces (see also #2 ).
C. Use another structure solver that already supports reading stresses (is there one already?).

This is relevant to #7 .

**Comment by derekrisseeuw** [comment]
In my branch [FSI_devStress](https://github.com/derekrisseeuw/openfoam-adapter/tree/FSI_devStress/FSI) I added the stress class. I plan to merge this branch soon with the FSI_dev branch on my fork. 

You will find that the code is very similar to the force class with a lot of code duplication. The difference between the classes is that the force is multiplied by the surface face areas to get the conservative quantity, while this is not done for the stresses. 

If I am correct, deal-ii can handle stresses?

**Comment by DavidSCN** [comment]
In general, you can choose in the deal.ii code, whether you want to calculate with stresses or with forces. But consider, that the deal.ii-precice version is currently a prototype. It could be useful for testing of course.

**Comment by uekerman** [comment]
Just for completion: 
Option D: Use connectivity in the structure solver to apply the action.

**Comment by MakisH** [comment]
This was closed by #125.
