### ISSUE TITLE
FSI: Support compressible solvers

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#42]
At the moment, we compute forces in `FSI/Force.C` (at the `FSI` branch for now) assuming a constant density and viscosity. In order to support compressible solvers as well, we need to abstract these in a way similar to the [KappaEffective](https://github.com/precice/openfoam-adapter/blob/master/CHT/KappaEffective.C) for CHT.

An open question here is how to validate the compressible FSI, as I am not aware of any literature on this at the moment. In other words, we are looking for something similar to the Turek-Hron FSI benchmark for compressible solvers.

We already had some discussion on this with @JSeuffert. Do you maybe have anything to add here?

This is relevant to #7.

**Comment by JSeuffert** [comment]
Thanks for making this an issue and I totally agree with you @MakisH .

The compressible solvers should all have a volScalarField called “thermo:mu” for the dynamic viscosity. So in my opinion the best would be to read this at the registry. Also the density should be read from the registry and not from the dictionary. 
I dont know the best solution how to structure it but maybe we can do it like the heat flux in the CHT module by implementing Force_incompessible and Force_compressible?

Regarding the verification of the compatibility of the module to different solver types, we could firstly use the Hron-Turek benchmark and solve it quasi-incompressible with a compressible solver and even with the multiphase solvers. 
At the moment I also do not know a specific compressible FSI benchmark, but I will do some more research.

**Comment by derekrisseeuw** [comment]
At the moment the code in the force class is very similar to the one in the openfoam function, but only the incompressible parts from that code are extracted. I think it would be quite straightforward to implement more of these code. 

See the Openfoam [forces.c](https://github.com/OpenFOAM/OpenFOAM-5.x/blob/7f7d351b741bf6406366a043cac98de56d2d44dd/src/functionObjects/forces/forces/forces.C)

**Comment by JSeuffert** [comment]
You are right @derekrisseeuw. That could be much easier. Thanks for this information!

**Comment by MakisH** [comment]
This is now supported on master.
