### ISSUE TITLE
Advance is called before boundary data is written in parallel

### ISSUE THREAD

**Issue by derekrisseeuw** [precice/openfoam-adapter#44]
When executing the openfoam adapter in parallel, the execute() function can call the precice advance before the boundary data has finished writing, which is done by the function writeCouplingData();

I noticed this when I put a 
`std::cout << "some text";
in one of the coupling classes. 

line 398
```
void preciceAdapter::Adapter::execute()
{
    if (errorsInConfigure)
    {
        // Handle any errors during configure().
        // See the comments in configure() for details.
        adapterInfo
        (
            "There was a problem while configuring the adapter. "
            "See the log for details.",
            "error"
       );
    }

    // The solver has already solved the equations for this timestep.
    // Now call the adapter's methods to perform the coupling.

    // Write the coupling data in the buffer
    writeCouplingData();

    // Advance preCICE
    advance();
```

**Comment by MakisH** [comment]
I am not sure that a delay in flushing `std::cout` in parallel simulations is a safe criterion here. Does this also appear when you use the `Foam::Info` stream? This should behave a bit more as expected.

**Comment by derekrisseeuw** [comment]
The `Foam::Info` stream recognises a parallel run and only prints messages for the master processor, thererfore I use the `std::cout` in this case, since it will print for every processor. I can't verify if it is a 'safe criterion'.

**Comment by derekrisseeuw** [comment]
I did not find any strange behaviour on the physical side, but I wouldn't expect those with my case either.

**Comment by MakisH** [comment]
I am closing this for now due to not enough evidence.
