### ISSUE TITLE
Releases and versioning

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#52]
We should make proper releases of the adapter, similarly to preCICE. This way, a user can directly let us know which version she is using, we can announce release changes, thank contributors etc.

Questions:
* Which version number do we start from? I vote for `0.1.0` or similar. If we gave `1.0`, it would give the false impression that the project is as mature as preCICE itself.
* Should we just release different variants of the code for each supported OpenFOAM version? If yes, how should they be named? See also #32.
* If we wanted provide packages for each version instead, what could they be? There is already a Spack package with OpenFOAM v1806. OpenFOAM usually looks at its own paths for libraries, we should be able to write on them, or edit these paths.

**Comment by MakisH** [comment]
I lately converge to the following idea:
- release the adapter every time there is a new OpenFOAM.com version
- name the releases with dates, similarly to the OpenFOAM versions, and assume that all versions up to this work (.com only).
- keep the OpenFOAM.org versions in different branches, but do not refer the user to them. Instead, release additional archives for .org, with a suffix in the version.

Semantic versioning does not make much sense here, since we do not have any specific API to maintain. We do not plan to change the configuration file significantly from now on, the main dependency that makes versioning complicated is OpenFOAM.

We do not expect any versioning issues coming from changes in preCICE.

An important question is what happens if we greatly refactor the adapter and introduce more dependencies. This could come by pull requests such as #150.

**Comment by uekerman** [comment]
Just discussed with @MakisH, I like option 3.

**Comment by uekerman** [comment]
> We do not expect any versioning issues coming from changes in preCICE

What do we do for a breaking preCICE release? A major release of the adapter, I guess?

**Comment by MakisH** [comment]
> > We do not expect any versioning issues coming from changes in preCICE
> 
> What do we do for a breaking preCICE release? A major release of the adapter, I guess?

If nothing changes for the user, then it should be a minor release for the adapter, I guess. One example I can think of is Atom and Electron: releasing Atom `1.55 -> 1.56`, they upgraded Electron `6.1.12 -> 9.3.5` ([details](https://github.com/atom/atom/releases/tag/v1.56.0)).

I am not sure how to define a "stable API" for an adapter, thus (as I wrote above), a standard semantic versioning seems to be non-fitting. Similarly, I can see that OpenFOAM cannot define that, thus OpenCFD chose the chronological format and the OpenFOAM Foundation increases the (now single) first digit with every release.

For preCICE, versioning is much more intuitive: one signature changes -> major version bump, new feature -> minor version bump.

**Comment by DavidSCN** [comment]
I like the idea of creating archives for any OpenFOAM distribution we support and this will probably also make it easier for the user to find the appropriate version (as tarball). We should aim to make the versioning as intuitive as possible. In my opinion, the user should be able to see: (1) which features are included in the adapter release ('major version', we could simply announce features supported by different major versions) and (2) which OpenFOAM version is compatible with this specific tarball. Including the release date in the versioning creates for me too much confusion with the OpenFOAM vendors ('I have a foundation version: can I use the adapte versionr `1.2012`'?). My vote goes also in the direction of option three, but without the year and adding the compatible OpenFOAM version as a suffix, e.g. `1.0.v2012` or `1.0.v8`, maybe even adding an OF acronym before the `v`. This would at least be the most intuitive variant for me. Major/minor and OpenFOAM releases and the corresponding versioning should be clear.

**Comment by MakisH** [comment]
Discussing with @DavidSCN and taking into account feedback from more interested parties, we conclude the following:

- Let's not add the OpenFOAM version in the adapter version: we will probably confuse the user, especially if we mix the version, such as `v1.2012.0_OpenFOAM8` (which version is this compatible with?).
- We do want the compatibility to be prominent **in the archive**, e.g. `v1.2.3_OpenFOAM2012`, `v1.2.3_OpenFOAM8`.
- By default our branches (i.e. our master/develop) and tutorials officially only support the latest .com and as many older versions as meaningful.
- Let's not trap ourselves into having to release too often, since we do not expect to have so heavy development.
- We are fine going with semantic versioning, defining the digits as follows:
  - Major: breaking changes, meaning that the existing tutorials need to be updated in order to run again.
    - In case a change is only due to OpenFOAM and changes the function obejct itself, we have a major version (breaking the API of our library).
    - In case a change is only due to OpenFOAM and only affects the tutorials, we ignore it in the adapter, we consider it in the tutorials.
  - Minor: new features (nearest-projection mapping, fluid-fluid coupling, ...). New tutorials may need this new version.
  - Bugfix / revision: small nice-to-have updates or bugfixes. The same tutorials run with any revision.
 
Therefore, we can safely incorporate `v1.0.0`. Reasons for the `1`:
- The adapter has been through a major change (YAML->dict)
- The adapter has been tested for quite some time.

**Comment by MakisH** [comment]
A few more points after discussing this with @uekerman:
- Let's directly use `com` / `org` in the archive names: it makes things clearer.
- We release also a named archive for the latest ESI version, to avoid confusion. Name: `v1.0.0_com1812-2012.tar.gz`.
- We add `_experimental` next to not-well-tested releases: `v1.0.0_org8_experimental.tar.gz`.
- We release bugfixes for the `.com` releases as soon as possible. For `.org`-specific bugfixes, we try to attach to any next release, since these would be changes in a different branch of the code.
