### ISSUE TITLE
FSI: Extend Force to turbulent flows

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#57]
Currently, in `FSI/Force.C`, we only support laminar flows (see `devRhoReff()`).

No warning is currently implemented.

More details to follow.

See also #42. Relevant to #7.

**Comment by derekrisseeuw** [comment]
Check out the fork of [efirvida ](https://github.com/efirvida/openfoam-adapter), I think he implemented most of the different types of forces already.

**Comment by MakisH** [comment]
This has been closed through #64.
