### ISSUE TITLE
Just can't get it installed...

### ISSUE THREAD

**Issue by kickflipin** [precice/openfoam-adapter#63]
Trying to install following https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-OpenFOAM-and-CalculiX

       on Ubuntu 18.04 using parallels on mac.

       I get scon error saying undefined fftw_taint and fftw_ialignment_of, ffftw_join_taint 
       Also same error on openfoam-adapter.

      Please let me know what else you need. 
      Or just let me know what ubuntu version and the trial was tested.
      I have just followed the instructions on the tutorial but it didn't get me anywhere.

**Comment by MakisH** [comment]
Dear @kickflipin,

this should be a platform-specific problem. We have tried it both on Ubuntu 16.04 and 18.04 (and other distributions), while I am not aware of anybody that tried it on macOS.

Let's please continue this discussion on [Gitter](https://gitter.im/precice/Lobby).
