### ISSUE TITLE
InitNull is not available on OpenFOAM v1706

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#76]
Here, change `1000` to `1706`:

https://github.com/precice/openfoam-adapter/blob/3bc68a013db5d59e4e1703864a633c14e3994e74/preciceAdapterFunctionObject.C#L56

**Comment by floli** [comment]
Note: On SuperMUC, using the `openfoam/v1706+` module, I had to uncomment the entire `if` block. Probably because `OPENFOAM_PLUS` is defined.

**Comment by MakisH** [comment]
@floli does #81 solve your issue? It's not easy for me to test it at the moment.

**Comment by MakisH** [comment]
Merged #81 in develop, closing the issue for now,
