### ISSUE TITLE
Support RBF mesh deformation methods

### ISSUE THREAD

**Issue by derekrisseeuw** [precice/openfoam-adapter#85]
**Problem**
The more recent versions of openFOAM have various mesh deformation functions: Laplacian or SBR stress mesh deformation. However, these methods proved not able to cope with large deformations found in many FSI applications. 

A more capable mesh deformation approach can be taken as the RBF mesh deformation posed by David Blom in FOAM-FSI, developed by Frank Bos in Foam-Extend. However, this particular implementation suffers from high memory usage for slightly larger meshes. Therefore a smart approach should be taken where a focus is put on sparse matrix systems to allow for large mesh deformations.

**Solution**
A new member of the [displacementMotionSolver](https://www.openfoam.com/documentation/guides/latest/api/classFoam_1_1displacementMotionSolver.html) class can be made based on RBF: `displacementRBFFvMotionSolver`. 

Since we do not want to alter the OpenFOAM source code, a separate part would need to be included in the OpenFOAM adapter.

**Comment by mfolkersma** [comment]
There is a group working on a new fluid structure interaction toolkit called [solids4foam](https://www.cfd-online.com/Forums/openfoam-cc-toolkits-fluid-structure-interaction/216865-purpose-sub-forum.html) which will support the "official" OpenFOAM. It includes RBF based mesh deformation.

**Comment by Lianxiali** [comment]
Any progress on `displacementRBFFvMotionSolver`? This is an interesting feature for FSI using preCICE!

**Comment by MakisH** [comment]
Closed by https://github.com/precice/openfoam-adapter/pull/241
