### ISSUE TITLE
Wiki missing nearest-projection mapping

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#90]
The following pages need to be extended to include our recent additions for nearest-projection mapping:

- [x] [Configuration](https://github.com/precice/openfoam-adapter/wiki/Configuration): include new options
- [x] [Home](https://github.com/precice/openfoam-adapter/wiki): include link to new tutorial
- [x] [Notes on preCICE](https://github.com/precice/openfoam-adapter/wiki/Notes-on-preCICE): update nearest-projection mapping status

The documentation needs quite some updates, but let's start from this.

**Comment by DavidSCN** [comment]
I will open up a new section for the NP configuration in the advanced configuration, since the settings might be confusing for beginners.

**Comment by DavidSCN** [comment]
Please review the wiki pages and close the issue or request changes. I think we should avoid too much documentation duplication.
