### ISSUE TITLE
Coupling OpenFOAM to 2D solvers could be easier

### ISSUE THREAD

**Issue by MakisH** [precice/openfoam-adapter#94]
# Context

We currently have several users that couple OpenFOAM (which only works in 3D) with 2D solvers. We usually treat this case as follows:
* Use a 3D solver interface: `<solver-interface dimensions="3">`.
* In the 3D solver, use only one cell in the out-of-plane direction (pseudo-2D) and define the interface as points on a line.
* In the 2D solver, give zero values for the out-of-plane field components (e.g. force in z-direction).

Examples are e.g.:
* [Tutorial for FSI with deal.II and OpenFOAM](https://github.com/precice/precice/wiki/Tutorial-for-FSI-with-deal.II-and-OpenFOAM)
* [Tutorial for CHT: Flow over a heated plate with OpenFOAM and FEniCS](https://github.com/precice/precice/wiki/Tutorial-for-CHT:-Flow-over-a-heated-plate-with-OpenFOAM-and-FEniCS)

# Problem

This approach has the following problems:
* For a face-nodes-based mesh, one point of the 2D solver has two equally-distanced neighbors on the 3D mesh (in most cases). This makes the nearest-neighbor mapping to act arbitrarily.
* RBF mapping, which is the usual workaround to the equal-distance issue, [needs to be configured to set a dead dimension](https://github.com/precice/precice/wiki/Mapping-Configuration#radial-basis-function-mapping).
* Further numerical issues with the coupling schemes (@uekerman).
* If a solver needs to assume the dimension of its partner (potentially scaling any received data), then the black-box assumption of preCICE weakens.

# Proposed solution

We are working on making preCICE compatible with mixed dimensions, but this feature will not be available anytime soon. Also, OpenFOAM is clearly the solver of choice of our users for the role of the Fluid participant, right now.

As an easier solution, @uekerman suggested that we have an option in the OpenFOAM adapter to define 3D or 2D preCICE interfaces. This would require multiple changes in the code, for which @DavidSCN already did some research.

Related to #30.

**Comment by BenjaminRueth** [comment]
There are two additional tutorials that are coming soon, where the 2D-3D issue is very relevant: [FSI with OpenFOAM and FEniCS](https://github.com/precice/tutorials/pull/38)
